# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - netbsd
      - openbsd
    goarch:
      - amd64
      - 386
      - arm
      - arm64
archives:
  -
    format: zip
    replacements:
      darwin: macOS
    files:
      - README.md
      - COPYING
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-beta"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
